### ISSUE TITLE
Twitter / X post only shows video

### ISSUE THREAD

**Issue by sultan-xh** [demjhonsilver/embedia-vue#1]
Hi,

Thanks for the fantastic work! Really appreciate this, especially when Vue lacks a good embed package. 

I noticed that if an X post contains a video, it only shows the video, not a card with all the other info. Could you please look and think if it's possible?

Thanks!

![2024-10-29 01_47_16-Savoring the UK_ Discover the Best Food Delights Across the Pond - XenHired](https://github.com/user-attachments/assets/03b5ff52-25b5-47d9-a867-870db7e6b48c)

**Comment by demjhonsilver** [comment]
I fixed the issue with embedding x.com, which now restores the embedded post with a card rather than just a video. Thank you for bringing this issue to my attention.

**Comment by sultan-xh** [comment]
Many thanks! It looks perfect now!

![image](https://github.com/user-attachments/assets/add7f89e-09ad-4405-8186-a013c450711f)
